---
title: "hw5_ilz2105"
author: "Lulu Zhang"
date: "11/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

__Problem 1__ 

```{r}
library(tidyverse)
library(rvest)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

For numeric variables, you should fill in missing values with the mean of non-missing values
For character variables, you should fill in missing values with "virginica"

```{r}
iris_with_missing
# replace some species with NA's
iris_with_missing[,"Species"] <- as.character(iris_with_missing[,"Species"])
iris_with_missing[c(1,50,100),"Species"] = NA

# replace some numeric with NA's
iris_with_missing[c(2,79,112),c("Sepal.Length","Petal.Length")] = NA



cleanData.func <- function(data){
  
  # identify character variables and numeric variables

  # numeric vars
  numericVars = which(sapply(data, is.numeric)==TRUE)
  # character vars
  characterVars = which(sapply(data, is.character)==TRUE)
  
  # replace NA character vars with "Virginica"
  for (i in 1:length(characterVars)){
    
    var = characterVars[[i]]
    
    data[is.na(data[,var]),var]="Virginica"
    
  }
  
  # replace NA numeric vars with the mean of that variable
  for (i in 1:length(numericVars)){
    
    var = numericVars[[i]]
    
    data[is.na(data[,var]),var]=mean(data[,var],na.rm = TRUE)
    
  }
  
  # return the cleaned data
  return(data)
  
}


iris_with_missing <- cleanData.func(iris_with_missing)
  
```

